#!/bin/sh

file=$1
seuil=$2

if [ -z "$seuil" ]; then
	echo "Usage: ./quickSeuil <fichier> <seuil>"
	exit 1
fi

./sort $file 0 $seuil
# 0 correspond l'algo "quicksort" avec premier élément comme pivot 

