
all: dynamique recuitSimule vorace

dynamique: dynamique.cpp exemplaire_struct.cpp
	g++ --std=c++14 -g -o -Wall $@ $^

recuitSimule: recuitSimule.cpp
	g++ --std=c++14 -g -o -Wall $@ $^
vorace: vorace.cpp
	g++ --std=c++14 -g -o -Wall $@ $^


